
set -g default-terminal "tmux-256color"
set -as terminal-features ",tmux-256color:RGB"
set -g extended-keys on

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1
set -g renumber-windows on
set -g escape-time 0
set -g mouse on
set -g remain-on-exit off
setw -g mode-keys vi

unbind '"'
unbind %

bind | split-window -h -c "#{pane_current_path}"

bind - split-window -v -c "#{pane_current_path}"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r ^ last-window

unbind -n M-Left
unbind -n M-Right
unbind -n M-Up
unbind -n M-Down

bind -n M-S-Left  select-pane -L
bind -n M-S-Right select-pane -R
bind -n M-S-Up    select-pane -U
bind -n M-S-Down  select-pane -D

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux reloaded"

set -g status-position bottom
set -g status-justify absolute-centre
set -g status-style 'fg=color7 bg=default'

set -g status-left ' #S'
set -g status-left-length 50
set -g status-left-style 'fg=color8'

set -g status-right-style 'fg=green bg=default'
set -g status-right "#{b:#{s|$HOME|~|:pane_current_path}} "
set -g status-right-length 50

setw -g window-status-format ' #I #[fg=gray]#W #[fg=gray]#F '

setw -g window-status-style 'fg=color8'
setw -g window-status-current-style 'fg=black bg=green'
setw -g window-status-current-format ' #I #W #F '

bind-key -n C-S-Left swap-window -t -1\; select-window -t -1
bind-key -n C-S-Right swap-window -t +1\; select-window -t +1

set -g status-interval 1
set -g xterm-keys on

set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
