set -g default-terminal "tmux-256color"
set -as terminal-features ",tmux-256color:RGB:usstyle"
set -g extended-keys on
set -g xterm-keys on
set -g escape-time 0
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
set -g allow-passthrough on

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1
set -g renumber-windows on
set -g mouse on
set -g remain-on-exit off
setw -g mode-keys vi

unbind '"'
unbind %

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind C-h swap-pane -t '{left-of}'
bind C-j swap-pane -t '{down-of}'
bind C-k swap-pane -t '{up-of}'
bind C-l swap-pane -t '{right-of}'

unbind -n M-Left
unbind -n M-Right
unbind -n M-Up
unbind -n M-Down

bind -n M-S-Left select-pane -L
bind -n M-S-Right select-pane -R
bind -n M-S-Up select-pane -U
bind -n M-S-Down select-pane -D

bind -r ^ last-window

bind-key -n C-S-Left swap-window -t -1 \; select-window -t -1
bind-key -n C-S-Right swap-window -t +1 \; select-window -t +1

bind K kill-window -a

set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=color7 bg=default'

set -g status-left ''
set -g status-right ' #S '
set -g status-right-length 50
set -g status-right-style 'fg=color8 bg=default'

setw -g window-status-format ' #I #W '
setw -g window-status-style 'fg=color8 bg=default'

setw -g window-status-current-format ' #I #[bold]#W#[nobold] '
setw -g window-status-current-style 'fg=black bg=green'

set -g set-titles on
set -g set-titles-string '#{pane_title}'

bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux reloaded"
