#!/bin/sh

# echo ""
# neofetch
# # echo ""

# cd ~
if [ "$TERM" = "foot" ]; then
  brr=$(od -An -N2 -i /dev/urandom | tr -d ' ')
  brr=$((brr % 100))

  if [ $((brr % 3)) -eq 0 ]; then
    fortune | cowsay
  elif [ $((brr % 10)) -eq 0 ]; then
    neofetch
  fi
fi
