
[window]
opacity = 0.9
dynamic_padding = true

blur = true
dynamic_title = true
# decorations = "Buttonless"

[colors.primary]
background = "#0F1419"
foreground = "#E6E1CF"

[colors.normal]
black   = "#0F1419"
red     = "#F07178"
green   = "#B8CC52"
yellow  = "#FFB454"
blue    = "#59C2FF"
magenta = "#D2A6FF"
cyan    = "#95E6CB"
white   = "#E6E1CF"

[colors.bright]
black   = "#4E5057"
red     = "#F07178"
green   = "#B8CC52"
yellow  = "#FFB454"
blue    = "#59C2FF"
magenta = "#D2A6FF"
cyan    = "#95E6CB"
white   = "#E6E1CF"

[font]
normal = { family = "SF Mono" }
size = 13

[terminal.shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session"]
