
[window]
opacity = 0.9
dynamic_padding = true

blur = true
dynamic_title = true
# decorations = "Buttonless"

[colors.primary]
background = "#0f1419"
foreground = "#f7f8f9"

[colors.normal]
black   = "#000000"
red     = "#ff3333"
green   = "#b8cc53"
yellow  = "#e6c547"
blue    = "#36a3d9"
magenta = "#f07178"
cyan    = "#95e6cb"
white   = "#ffffff"

[colors.bright]
black   = "#323232"
red     = "#ff6565"
green   = "#eafe84"
yellow  = "#fff779"
blue    = "#68d5ff"
magenta = "#ffa3a9"
cyan    = "#c7fffd"
white   = "#ffffff"

[font]
normal = { family = "Liga SFMono Nerd Font" }
size = 13

[terminal.shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session"]
