
[window]
opacity = 0.9
dynamic_padding = true

blur = true
dynamic_title = true
# decorations = "Buttonless"

[colors.primary]
background = '#0A0E14'
foreground = '#B3B1AD'

[colors.normal]
black   = '#01060E'
red     = '#EA6C73'
green   = '#91B362'
yellow  = '#F9AF4F'
blue    = '#53BDFA'
magenta = '#FAE994'
cyan    = '#90E1C6'
white   = '#C7C7C7'

[colors.bright]
black   = '#686868'
red     = '#F07178'
green   = '#C2D94C'
yellow  = '#FFB454'
blue    = '#59C2FF'
magenta = '#FFEE99'
cyan    = '#95E6CB'
white   = '#FFFFFF'

[font]
normal = { family = "SF Mono" }
size = 13

