#!/bin/sh

# if [ "$TERM" = "foot" ] || [ "$TERM" = "alacritty" ] || [ "$TERM" = "xterm-ghostty" ] || [ "$TERM" = "xterm-kitty" ] || [ "$TERM" = "xterm-256color" ]; then
#     	fortune | cowsay
# 
# 	showTodo
# fi

if [ "$TERM" = "xterm-ghostty" ]; then
	if [ -z "$TMUX" ]; then
		tmux attach -t default || tmux new -s default
	fi
fi
